Download Dataset From Kaggle

In [2]:
!kaggle datasets list -s Iris

ref                                                                 title                                              size  lastUpdated          downloadCount  voteCount  usabilityRating  
------------------------------------------------------------------  ------------------------------------------------  -----  -------------------  -------------  ---------  ---------------  
datasets/uciml/iris                                                 Iris Species                                        4KB  2016-09-27 07:38:05         266503       2916  0.7941176        
datasets/arshid/iris-flower-dataset                                 Iris Flower Dataset                               1010B  2018-03-22 15:18:06          49238        430  0.8235294        
datasets/vikrishnan/iris-dataset                                    Iris Dataset                                       999B  2017-08-03 16:00:44           3619         28  0.7647059        
datasets/therohk/ireland-historical-news          

In [3]:
!kaggle datasets download shantanuss/iris-flower-dataset --unzip 


  0%|          | 0.00/1.31k [00:00<?, ?B/s]
100%|##########| 1.31k/1.31k [00:00<00:00, 672kB/s]


Import Needed Module

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import tensorflow as tf

Show First 5 Data

In [3]:
bunga ='Iris_flower_dataset.csv'
flower_data = pd.read_csv(bunga)
flower_data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Show Data Info

In [4]:
flower_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


Label Encoder

In [5]:
X = flower_data.iloc[:, 1:-1].values
y = flower_data.iloc[:, -1].values
# le = LabelEncoder()
# y = le.fit_transform(y)
print(y[:5])
print()
print(X[:5])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Split Train And Test Data

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 0)

Get Flower Species

In [10]:
species = []
for i in y_train:
    if i not in species:
        species.append(i)
species

['Iris-setosa', 'Iris-virginica', 'Iris-versicolor']

KNN

In [11]:
knn = KNeighborsClassifier(n_neighbors=len(species))

In [13]:
knn.fit(X_train, y_train)
knn.predict(X_test)

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor'